_json.id pin.id
json.name pin.name
json.url pin.url
json.text pin.text
json.boardId pin.board_id
json.latitude pin.latitude
json.longitude pin.longitude
json.category_id pin.category_id
json.category pin.category.name