# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a072fbe7898398bf55f390f3bf1c3b8aec62a7b42a1c840c6cd1e0aad84dd177f07cb155be9610b478f3a62667572e8511844e5368d652a75132c07f819c411

test:
  secret_key_base: d8741ff102e0d2e2815b8deb91dc9a4e483b0eded34ad5da96dd3275f2f4e93364d65f246db6470f2261c51c092f86b35cdbd761cdc346ca6bfb274a6e49bbc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
